import { Job, Application, ResumeBankEntry } from './types';

export const INITIAL_JOBS: Job[] = [
  {
    id: 'job-1',
    title: 'Senior Full Stack Developer (Next.js & Node.js)',
    description: 'We are seeking an experienced Senior Full Stack Developer to lead the architecture and deployment of enterprise web applications for our global clients. You will work on high-availability cloud platforms and mentor junior developers.',
    responsibilities: [
      'Design scalable frontend architectures using Next.js and TypeScript',
      'Build high-performance microservices and RESTful API endpoints',
      'Optimize SQL database performance and manage cloud integrations',
      'Collaborate closely with UI/UX designers and product managers'
    ],
    skills: ['Next.js', 'React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Tailwind CSS', 'Docker'],
    location: 'Mumbai, Maharashtra (Hybrid)',
    experience: '5+ Years',
    salary: '₹18,00,000 - ₹24,00,000 P.A.',
    employment_type: 'Full-time',
    status: 'active',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'job-2',
    title: 'Lead Talent Acquisition Manager',
    description: 'Drive end-to-end recruitment strategies for senior executive positions across IT, Finance, and Consulting verticals. Perfect opportunity for an HR leader looking to scale enterprise teams.',
    responsibilities: [
      'Manage full lifecycle hiring for executive and niche technical roles',
      'Build talent pipelines and conduct structured interviews',
      'Partner with enterprise business stakeholders to clarify workforce planning',
      'Mentor junior recruiters and optimize ATS workflows'
    ],
    skills: ['Talent Acquisition', 'Executive Search', 'Technical Recruitment', 'HR Strategy', 'ATS'],
    location: 'Bengaluru, Karnataka (On-site)',
    experience: '6+ Years',
    salary: '₹15,00,000 - ₹20,00,000 P.A.',
    employment_type: 'Full-time',
    status: 'active',
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'job-3',
    title: 'UI/UX Product Designer (iOS & Web)',
    description: 'Join a fast-growing product design studio crafting iOS-first mobile designs, modern design systems, and web interfaces. Work with international product teams.',
    responsibilities: [
      'Create low and high fidelity wireframes and interactive prototypes in Figma',
      'Develop design tokens and component libraries following iOS Human Interface Guidelines',
      'Conduct usability testing sessions with real users',
      'Work directly with frontend engineers for seamless implementation'
    ],
    skills: ['Figma', 'UI/UX Design', 'Design Systems', 'iOS Guidelines', 'Prototyping', 'User Research'],
    location: 'Remote',
    experience: '3+ Years',
    salary: '₹12,00,000 - ₹16,00,000 P.A.',
    employment_type: 'Full-time',
    status: 'active',
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: 'job-4',
    title: 'Cloud DevOps Engineer (AWS & Kubernetes)',
    description: 'Manage infrastructure automation, CI/CD pipelines, and cloud security for high-traffic SaaS platforms. Ideal for engineers passionate about zero-downtime deployments.',
    responsibilities: [
      'Build and maintain Terraform IAC templates across multi-region AWS environments',
      'Configure Kubernetes clusters (EKS) and monitor service metrics',
      'Implement zero-downtime deployment pipelines with GitHub Actions',
      'Enforce cloud security compliance and cost optimization'
    ],
    skills: ['AWS', 'Kubernetes', 'Docker', 'Terraform', 'CI/CD', 'Python', 'Linux'],
    location: 'Pune, Maharashtra (Hybrid)',
    experience: '4+ Years',
    salary: '₹14,00,000 - ₹19,00,000 P.A.',
    employment_type: 'Full-time',
    status: 'active',
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'job-5',
    title: 'Financial Analyst & Risk Manager',
    description: 'Provide quantitative financial modeling, corporate budgeting, and risk mitigation strategies for multinational corporate clients.',
    responsibilities: [
      'Perform corporate valuation, forecasting, and scenario analysis',
      'Prepare monthly executive dashboard reports',
      'Evaluate investment risks and capital allocation efficiency',
      'Coordinate with audit and compliance teams'
    ],
    skills: ['Financial Modeling', 'Corporate Finance', 'Excel/VBA', 'Risk Analysis', 'Power BI'],
    location: 'Delhi NCR (On-site)',
    experience: '3+ Years',
    salary: '₹10,00,000 - ₹14,00,000 P.A.',
    employment_type: 'Full-time',
    status: 'active',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'job-6',
    title: 'Data Scientist (Machine Learning & NLP)',
    description: 'Develop predictive analytics models and generative AI workflows to solve complex enterprise data problems for healthcare and fintech clients.',
    responsibilities: [
      'Build LLM fine-tuning and retrieval-augmented generation (RAG) pipelines',
      'Develop predictive classification and regression models in Python',
      'Clean, engineer features, and validate massive datasets',
      'Deploy ML models into production API endpoints'
    ],
    skills: ['Python', 'PyTorch', 'Machine Learning', 'NLP', 'SQL', 'Scikit-Learn', 'FastAPI'],
    location: 'Hyderabad, Telangana (Remote)',
    experience: '4+ Years',
    salary: '₹16,00,000 - ₹22,00,000 P.A.',
    employment_type: 'Full-time',
    status: 'active',
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
];

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: 'app-1',
    job_id: 'job-1',
    job_title: 'Senior Full Stack Developer (Next.js & Node.js)',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@example.com',
    phone: '+91 98765 43210',
    qualification: 'B.Tech in Computer Science',
    experience: '6 Years',
    location: 'Mumbai, MH',
    linkedin: 'https://linkedin.com/in/aarav-sharma-demo',
    resume_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'app-2',
    job_id: 'job-3',
    job_title: 'UI/UX Product Designer (iOS & Web)',
    name: 'Priya Verma',
    email: 'priya.verma@example.com',
    phone: '+91 98123 45678',
    qualification: 'Bachelor of Design (B.Des)',
    experience: '4 Years',
    location: 'Bengaluru, KA',
    linkedin: 'https://linkedin.com/in/priya-verma-ui',
    resume_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

export const INITIAL_RESUME_BANK: ResumeBankEntry[] = [
  {
    id: 'rb-1',
    name: 'Rohan Mehta',
    email: 'rohan.mehta@example.com',
    phone: '+91 99887 76655',
    qualification: 'MBA in Human Resource Management',
    experience: '5 Years',
    preferred_role: 'HR Business Partner / Talent Lead',
    preferred_location: 'Mumbai / Pune / Hybrid',
    skills: ['HR Generalist', 'Performance Management', 'Employee Relations', 'HRIS'],
    notes: 'Open for immediate joiner roles in fintech or SaaS tech companies.',
    resume_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'rb-2',
    name: 'Ananya Deshmukh',
    email: 'ananya.d@example.com',
    phone: '+91 97654 32109',
    qualification: 'M.Sc in Data Analytics',
    experience: '3 Years',
    preferred_role: 'Data Engineer / BI Analyst',
    preferred_location: 'Remote / Bengaluru',
    skills: ['SQL', 'Snowflake', 'dbt', 'Tableau', 'Python'],
    notes: 'Strong background in data modeling and cloud data pipelines.',
    resume_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];
